### ISSUE TITLE
Add ban-length override to browser extension

### ISSUE THREAD

**Issue by TerryPotatoFace** [Kaifurn/LSF-Utilities-Tracker#6]
The bot now supports adding custom ban lengths so the extension should support it as well. Ideally it would be nice to have a drop down with the relevant escalations for the selected rule and have it default to whatever the next escalation is, but that would probably require the reading of the usernotes to know what the current ban length should be.

At minimum it could just be a ban override checkbox that then displays a text input where the ban length could be manually entered.

**Comment by Kaifurn** [comment]
Added a duration override input as a textbox with an autocomplete dropdown that has the standard ban lengths as options.
